version: "3"

services:
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "4318:4318" # otelcol HTTP/JSON
      - "16686:16686" # UI and API

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=otel
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  mysql:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=test
    ports:
      - "3306:3306"

  localstack:
    image: localstack/localstack:s3-latest
    ports:
      - "4566:4566"
    volumes:
      - ./volume:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
