resolver: lts-19.2

packages:
- api
- sdk
- otlp
- examples/aws-s3
# - examples/grpc-echo # only able to be built with cabal
- examples/hdbc-mysql
- examples/http-server
- examples/yesod-minimal
- examples/yesod-subsite
- exporters/handle
- exporters/in-memory
# - exporters/jaeger
- exporters/otlp
# - exporters/prometheus
- instrumentation/amazonka
- instrumentation/cloudflare
- instrumentation/conduit
# - instrumentation/grpc-haskell # only able to be built with cabal
- instrumentation/hdbc
- instrumentation/hdbc-mysql
- instrumentation/hedis
# - instrumentation/herp-logger-datadog # 本家に PR しない
- instrumentation/hspec
- instrumentation/http-client
- instrumentation/persistent
- instrumentation/persistent-mysql
- instrumentation/postgresql-simple
- instrumentation/wai
- instrumentation/yesod
- propagators/b3
- propagators/datadog
# - propagators/jaeger
- propagators/w3c
- utils/exceptions
- vendors/datadog

extra-deps:
- hspec-2.11.7@sha256:2869580a2a29e7beb6268ea3dc561583f4ae229ed1f47fb1c92e8c09ce35acec,1763
- hspec-core-2.11.7@sha256:90d8873356d7e15f843bc523360e206e8e356ff6b82a1fa4b3889dc31d073ea1,6814
- hspec-discover-2.11.7@sha256:6307eb16d308258a99a242025df50217d835ba0a3f205b1202a100a175877b38,2169
- hspec-expectations-0.8.4@sha256:4237f094a7931202ff57ac6475542b0b314b50a7024550e2b6eb87cfb0d4ff93,1702
- thread-utils-context-0.2.0.0@sha256:7863e568c7a43cd21616342d20484d4c962aaa9710619f104c6fb7ee32273940,1883
- thread-utils-finalizers-0.1.1.0@sha256:24944b71d9f1d01695a5908b4a3b44838fab870883114a323336d537995e0a5b,1381
- github: ryantm/hdbc-mysql
  commit: 80f8077b29ee27bce4141b385a8b28f42cbbbe46 # HEAD of master at 2023-12-19

nix:
  enable: true
  packages: [libffi, mysql80, openssl, pcre, postgresql, zlib, zstd]
