on:
  push:
  pull_request:
jobs:
  stack-ghc-8_12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-22.11
      - uses: haskell/actions/setup@v2
        with:
          enable-stack: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            .stack-work
          key: stack-${{ runner.os }}-8.12-${{ hashFiles('stack-ghc-8.12.yaml.lock') }}
          restore-keys: |
            stack-${{ runner.os }}-8.12
      - run: stack --stack-yaml stack-ghc-8.12.yaml build --only-dependencies
      - run: stack --stack-yaml stack-ghc-8.12.yaml build
      - run: stack --stack-yaml stack-ghc-8.12.yaml test
      - run: stack --stack-yaml stack-ghc-8.12.yaml bench --no-run-benchmarks
  stack-ghc-9_0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-22.11
      - uses: haskell/actions/setup@v2
        with:
          enable-stack: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            .stack-work
          key: stack-${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}
          restore-keys: |
            stack-${{ runner.os }}
      - run: stack build --only-dependencies
      - run: stack build
      - run: stack test
      - run: stack bench --no-run-benchmarks
  stack-ghc-9_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-22.11
      - uses: haskell/actions/setup@v2
        with:
          enable-stack: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            .stack-work
          key: stack-${{ runner.os }}-9.2-${{ hashFiles('stack-ghc-9.2.yaml.lock') }}
          restore-keys: |
            stack-${{ runner.os }}-9.2
      - run: stack --stack-yaml stack-ghc-9.2.yaml build --only-dependencies
      - run: stack --stack-yaml stack-ghc-9.2.yaml build
      - run: stack --stack-yaml stack-ghc-9.2.yaml test
      - run: stack --stack-yaml stack-ghc-9.2.yaml bench --no-run-benchmarks
  cabal-ghc-9_0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-22.11
      - uses: actions/cache@v3
        with:
          path: ~/.cabal
          key: cabal-${{ runner.os }}-9.0-${{ hashFiles('cabal.project.freeze') }}
      - run: nix-shell --run 'cabal update'
      - run: nix-shell --run 'cabal v2-build --only-dependencies all'
      - run: nix-shell --run 'cabal v2-build all'
      - run: nix-shell --run 'cabal v2-test all'
      - run: nix-shell --run 'cabal v2-build --enable-benchmarks all'
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fourmolu/fourmolu-action@v6
