on: [push]
name: build
jobs:
  runhaskell:
    name: Build everything
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          # ghc-version: '8.8.3' # Exact version of ghc to use
          # cabal-version: 'latest'. Omitted, but defaults to 'latest'
          enable-stack: true
          stack-version: 'latest'
      - uses: cachix/install-nix-action@v17
      - uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            .stack-work
          key: stack-${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}
          restore-keys: |
            stack-${{ runner.os }}
      # 9.2 testing support?
      - uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            .stack-work
          key: stack-${{ runner.os }}-9.2-${{ hashFiles('stack-ghc-9.2.yaml.lock') }}
          restore-keys: |
            stack-${{ runner.os }}-9.2
      - run: stack test
      - run: stack test --stack-yaml stack-ghc-9.2.yaml
